258 merge workflow assets (#259)
* moved workflow dialob form and wrench flow information to stencil

* finding form id from form name and tag if id is not set

* organized code, imports

* Form and flow data to topic link

* fixed migrations

* fixed tests for workflow and links, having form and flow fields

* workflow configuration (form, flow) in stencil

* form name alignment to use 50% of space

* texts for stencil services translations

* fixed request header for dialob: it should be json otherwise non-english characters will give error in dialob like:
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Invalid UTF-8 middle byte 0x3f

* fixed workflow attributes copying to stencil client

* fixed timestamps handling for start and end date, it results in error when field already contains timestamp

* look for workflow to get form info when service does not have it

* added requirement of form and flow data to be able to complete form

* removed empty selection from flow names

* added property which indicates whether to use form id or not when
creating questionnaire

* removed unused imports

* fill form id always via ui

---------

Co-authored-by: Olev Mutso <olev.mutso@resys.io>